# Generated by Django 4.0.1 on 2024-06-03 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 6, 3, 18, 39, 58, 864209, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
